# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - env:
      - CGO_ENABLED=0
    # Disable binary building for libraries
    skip: true
    # But still build for these platforms (for testing)
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    # Include source files
    files:
      - "*.go"
      - "go.*"

# Remove changelog filters (keep default behavior)
changelog: {}

release:
  github:
    owner: obi2na  # Add your GitHub username
    name: exModuleGoReleaser     # Add your repo name

# Remove before.hooks if you're not using them
# Remove format_overrides since we're only using tar.gz